name: xts_data_importer
description: "A new Flutter project for importing XTS data."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 데이터베이스 ORM
  drift: ^2.17.0
  
  # 각 플랫폼에 맞는 SQLite 라이브러리 포함
  sqlite3_flutter_libs: ^0.5.20
  
  # 데이터베이스 파일 경로 탐색
  path_provider: ^2.1.3
  path: ^1.9.0
  
  # CSV 파일 파싱
  csv: ^6.0.0

  # 파일 선택기를 위한 패키지 추가
  file_picker: ^10.3.1 
  permission_handler: ^12.0.1 # 최신 버전 확인 권장

  cupertino_icons: ^1.0.6

  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Drift 코드 생성을 위한 도구
  build_runner: ^2.4.9
  drift_dev: ^2.17.0

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.0

flutter:
  uses-material-design: true

  # CSV 파일을 프로젝트 자산으로 등록
  assets:
    - assets/cts-data1.csv
