name: google_auth_helper
description: Flutter-first Google Auth Helper with extensible XTS parsing and Firestore REST integration.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dart_jsonwebtoken: ^3.3.2
  fl_chart: ^1.1.1
  flutter_riverpod: ^3.3.0
  http: ^1.6.0
  path: ^1.9.1
  shared_preferences: ^2.5.4
  xml: ^6.6.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

