name: test_data_collect
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  drift: ^2.17.0
  sqlite3: ^2.4.0
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.17.0
  lints: ^6.0.0
  test: ^1.25.6
